### ISSUE TITLE
Week 2 Day 2 Code Review

### ISSUE THREAD

**Issue by Becky449** [GraceAbike/Awesome-BooksEs6#2]
## Great work on your project so far 💯 😄.
#Color combination on point
#Form validation working perfectly
#Proffessional commit messages.
##However, some issues may require your attention. They include the following :
#When a new book is added twice, duplicate copies of the same book are viewed. Kindly use IDs to specify different books 👍

**Comment by GraceAbike** [comment]
@Becky449 thanks for your comments.
